# SPDX-License-Identifier: GPL-2.0+

obj-y += starfive-clkgen.o
obj-y += starfive-clkgen-data.o
obj-y += starfive-clkgen-util.o
obj-y += starfive-clkgen-common.o
obj-y += starfive-clkgen-div.o
obj-y += starfive-clkgen-fdiv.o
obj-y += starfive-clkgen-fixed.o

